### ISSUE TITLE
(Overview) - My Assets Widget

### ISSUE THREAD

**Issue by atapas** [atapas/vento-client#45]
A Quick way to show the Assets I own/manage/consume.

**Comment by atapas** [comment]
- If a Lab owner logs in, he/she gets the summary of the assets they Own
- If a Consumer logs in, he/she gets the summary of the assets they consumed

# Summary Information
- Number of Physical Assets with types
- Number of Softwares
- Total Assets
- Number of renewable assets(near to expiry)
- State of the assets
- Assets underused
- Think of more usecases

## Additional Criteria
- All the numbers in this widgets will have links to drill down to asset list page to list relevant assets.
- All the clickable representations in this widget will drill down to asset list page to list relevant assets.

**Comment by IAMLEGION98** [comment]
### Section 1
When the log in happens, a service will be called. To get the **Number of assets under the Lab Owner**, a get query (Query1) will be called, creating **owner_assets** object having details of all assets currently owned by the Lab Owner.
A key-value pair array generation function creates **owner_asset_type** object having key value pairs of the asset_id and qty of each.
<br/>
![Section1](https://user-images.githubusercontent.com/20149005/81284942-6b5fb400-907c-11ea-8f33-e44380c34461.jpg)

**Comment by VarshaRavichandran** [comment]
### Section 2
- To get the software assets, the section 1 object (owner assets) can be used to fetch only the software assets owned by the owner currently logged in.
- To get the **Number of assets under the Lab Owner that are about to expire**, a get query (Query2) will be called, creating **owner_assets** object having details of all assets currently owned by the Lab Owner but with the contractEndDate checked, eg: 30 days till the date of expiry.
![image](https://user-images.githubusercontent.com/33756351/81288250-e6779900-9081-11ea-9059-6da436f9625a.png)

- To get the total number of assets, the total number of records fetched from Query 1 (Section 1) can be used -> data.length.

### Section 3
To get the state of assets and its usage:
![image](https://user-images.githubusercontent.com/33756351/81290081-0fe5f400-9085-11ea-9bbe-d93b90db32f1.png)

**Comment by IAMLEGION98** [comment]
### Section 2
The number of **renewable assets with expiry** approaching can be accessed by calling query. <br/>
**State of assets** uses matching of objects returning from 2 queries to create a key-value pair data set of **asset_id** and the **consumption count**. The fewer consumption count assets can be observed.
The data can be plotted in Bar chart
![Section2](https://user-images.githubusercontent.com/20149005/81291046-bb437880-9086-11ea-8f78-836adf5074bc.jpg)

**Comment by IAMLEGION98** [comment]
> ### Section 1
> When the log in happens, a service will be called. To get the **Number of assets under the Lab Owner**, a get query (Query1) will be called, creating **owner_assets** object having details of all assets currently owned by the Lab Owner.
> A key-value pair array generation function creates **owner_asset_type** object having key value pairs of the asset_id and qty of each.
> 
> 
> ![Section1](https://user-images.githubusercontent.com/20149005/81284942-6b5fb400-907c-11ea-8f33-e44380c34461.jpg)

Just an option: Total number of assets to be displayed by a Title number widget
<img width="215" alt="totalnumber" src="https://user-images.githubusercontent.com/20149005/81291705-ed090f00-9087-11ea-8a02-2f7d2a0bfbbb.PNG">

The asset types with their quantity could be displayed in pie chart as:
<img width="369" alt="types of assets" src="https://user-images.githubusercontent.com/20149005/81291759-09a54700-9088-11ea-9a11-5bea780fbc3a.PNG">

**Comment by IAMLEGION98** [comment]
> ### Section 2
> * To get the software assets, the section 1 object (owner assets) can be used to fetch only the software assets owned by the owner currently logged in.
> * To get the **Number of assets under the Lab Owner that are about to expire**, a get query (Query2) will be called, creating **owner_assets** object having details of all assets currently owned by the Lab Owner but with the contractEndDate checked, eg: 30 days till the date of expiry.
>   ![image](https://user-images.githubusercontent.com/33756351/81290377-969ad100-9085-11ea-935f-2035c8cdd107.png)
> * To get the total number of assets, the total number of records fetched from Query 1 (Section 1) can be used -> data.length.
> 
> ### Section 3
> To get the state of assets and its usage:
> ![image](https://user-images.githubusercontent.com/33756351/81290432-b0d4af00-9085-11ea-8467-cf00324d870b.png)

The Assets that are nearing expiry and overused could be displayed in a widget as below. The **onclick** would direct it to the **Assetlist** page listing out those assets in the table.

<img width="263" alt="overusedandexpiry" src="https://user-images.githubusercontent.com/20149005/81292207-cbf4ee00-9088-11ea-8816-8f542db0bd76.PNG">

**Comment by IAMLEGION98** [comment]
## Version 0.1 

![Overview_v0 1](https://user-images.githubusercontent.com/20149005/81399869-77657780-9149-11ea-9284-9363cda613e2.jpg)
_* added asset utilization score_

**Comment by VarshaRavichandran** [comment]
## Version 0.2

![image](https://user-images.githubusercontent.com/33756351/81407209-a1726600-9158-11ea-87bc-7a2feb8b30d4.png)

_* added all users of assets owned by a particular user

**Comment by IAMLEGION98** [comment]
**Usecases**    (To be threaded if new)
- Number of Physical Assets with types
- Number of Softwares
- Total Assets
- Number of renewable assets(near to expiry)
- State of the assets
- Assets underused
<br/>

- All users of a particular asset
- Asset Utilization score 
- Asset consumed over the last 30 days (Plot)

**Comment by atapas** [comment]
Do we have data for most of it envisioned here?

**Comment by IAMLEGION98** [comment]
> Do we have data for most of it envisioned here?

Yes, we can Sir. We included the data derivation process above. Calling the API, we need to run some time invasive process. But it can be done

**Comment by atapas** [comment]
Please provide following information in tabular format:

1. Persona
2. UseCase
3. Data Availability (Complete or Partial)
4. Complexity (S - 1 to 2 days, M - 2 to 4 days, L - >=7 days)

**Comment by atapas** [comment]
Once the above information is provided and we concluded what is the set to start with, please provide the design(Low Level) for

- How to get the data to component(from services)
- How to drill-down from the components.

**Comment by IAMLEGION98** [comment]
### **Objectives for widget design**
| S.No | Use Case          | Persona      | Data Availability | Complexity |
|-------------| ------------------------|-------------| --------|--------|
| 1 |Total Assets | Lab Owner, Consumer| Complete| Small |
| 2 |Number of Software's | Lab Owner, Consumer| Complete| Small |
| 3 |Number of Hardware's | Lab Owner, Consumer| Complete| Small |
| 4 | Grouping of assets with type | Lab Owner| Partial | Medium |
| 5 | Software's that need to be renewed (about to expire and lapsed expiry) | Lab Owner, Consumer| Complete| Small |
| 6 | Hardware usage (of VM's etc) based on space, CPU and RAM | Lab Owner| Partial| Large |
| 7 | Software usage based on number of consumers | Lab Owner| Partial| Medium |
| 8 |Hardware usage (underused) based on state (key= 'OS Summary') | Lab Owner| Partial| Medium |
| 9 | Listing of consumers under the owner's assets | Lab Owner | Complete| Medium |

**Comment by atapas** [comment]
Hi All,

I have added a column called Phase. Anything marked as Phase 1 has a completion date of 22nd May.

Please focus on those.

Let me know when the service design has been done.

**Comment by atapas** [comment]
> ### **Objectives for widget design**
> S.No	Use Case	Persona	Data Availability	Complexity	Phase
> 1	Total Assets	Lab Owner, Consumer	Complete	Small	Phase 1
> 2	Number of Software's	Lab Owner, Consumer	Complete	Small	Phase 1
> 3	Number of Hardware's	Lab Owner, Consumer	Complete	Small	Phase 1
> 4	Grouping of assets with type	Lab Owner	Partial	Medium	Phase 1
> 5	Software's that need to be renewed (about to expire and lapsed expiry)	Lab Owner, Consumer	Complete	Small	Phase 1
> 6	Hardware usage (of VM's etc) based on space, CPU and RAM	Lab Owner	Partial	Large	
> 7	Software usage based on number of consumers	Lab Owner	Partial	Medium	
> 8	Hardware usage (underused) based on state (key= 'OS Summary')	Lab Owner	Partial	Medium	
> 9	Listing of consumers under the owner's assets	Lab Owner	Complete	Medium	Phase 1

- Usecase 1 to Usecase 3 can be clubbed into one Widget.

**Comment by IAMLEGION98** [comment]
### Service layer for the Overview widgets 
<img width="810" alt="calls" src="https://user-images.githubusercontent.com/20149005/81682619-8e220c00-9472-11ea-92df-bf44b67ddeec.PNG">

### Calling the service layer for a sample widget in Overview page
<img width="914" alt="getinoverview" src="https://user-images.githubusercontent.com/20149005/81682848-e35e1d80-9472-11ea-870b-0f87e7a11666.PNG">

**Comment by atapas** [comment]
@IAMLEGION98 please open the PR

**Comment by IAMLEGION98** [comment]
> @IAMLEGION98 please open the PR

Done Sir. PR is created
